tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bat"
brew "direnv"
brew "node"
brew "python"
brew "python3"
brew "mackup"
brew "mas"
brew "telnet"
brew "tree"
cask "gitkraken"
cask "ngrok"
cask "postman"
cask "dropbox"
cask "1password"
cask "iterm2"
cask "java"
cask "visual-studio-code"
cask "firefox"
cask "google-chrome"
cask "slack"
cask "font-fira-code"
cask "dbeaver-community"
mas "Magnet", id: 441258766
mas "Monosnap", id: 540348655
